polls_app/urls.py
from django.urls import path

from . import views

app_name = "polls_app"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls_app.urls")),
    path("admin/", admin.site.urls),
]

polls_app/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self) -> str:
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_text

polls_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .models import Question, Choice
from django.views import generic


class IndexView(generic.ListView):
    template_name = "polls_app/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls_app/detail.html"


class ResultsView(generic.DeleteView):
    model = Question
    template_name = "polls_app/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls_app/detail.html",
            {"question": question, "error_message": "You didn't select a choice"},
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls_app:results", args=(question.id,)))

polls_app/templates/polls_app/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Detail</title>
  </head>
  <body>
    <form action="{% url 'polls_app:vote' question.id %}" method="post">
      {% csrf_token %}
      <fieldset>
        <legend>
          <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
        {% endif %} {% for choice in question.choice_set.all %}
        <input
          type="radio"
          name="choice"
          id="choice{{forloop.counter}}"
          value="{{choice.id}}"
        />
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
        <br />
        {% endfor %}
      </fieldset>
      <input type="submit" value="Vote" />
    </form>
  </body>
</html>

polls_app/templates/polls_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'polls_app/styles.css' %}" />
    <title>Polls</title>
  </head>
  <body>
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
      <li>
        <a href="{% url 'polls_app:detail' question.id %}"
          >{{ question.question_text }}</a
        >
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

polls_app/templates/polls_app/results.html
<h1>{{question.question_text}}</h1>
<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}
  </li>
  {% endfor %}
</ul>
<a href="{% url 'polls_app:detail' question.id%}">Vote again?</a>

templates/base_site.html
{% extends "admin/base.html" %} 
{% block title %} 
{% if subtitle %} 
{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('Django site admin') }} 
{% endblock %} 
{% block branding %}
<h1 id="site-name">
  <a href="{% url 'admin:index' %}">Polls app</a>
</h1>
{% endblock %} {% block nav-global %}{% endblock %}

templates/index.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content %}
<div id="content-main">
  {% include "admin/app_list.html" with app_list=app_list show_changelinks=True %}
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% translate 'Recent actions' %}</h2>
        <h3>{% translate 'My actions' %}</h3>
            {% load log %}
            {% get_admin_log 10 as admin_log for_user user %}
            {% if not admin_log %}
            <p>{% translate 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                    {{ entry.object_repr }}
                {% else %}
                    <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br>
                {% if entry.content_type %}
                    <span class="mini quiet">{% filter capfirst %}{{ entry.content_type.name }}{% endfilter %}</span>
                {% else %}
                    <span class="mini quiet">{% translate 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
{% endblock %}